Add main dockerfile

diff --git a/Backend/docker/cpp-runner/Dockerfile b/Backend/docker/cpp-runner/Dockerfile
--- a/Backend/docker/cpp-runner/Dockerfile
+++ b/Backend/docker/cpp-runner/Dockerfile
@@ -1,13 +1,17 @@
 FROM alpine:latest
+
 RUN apk add --no-cache build-base bash
 
 WORKDIR /app
-RUN gcc_version=$(ls /usr/include/c++ | grep -E '^[0-9]+') || gcc_version=10 && \
+
+RUN gcc_version=$(ls /usr/include/c++ | grep -E '^[0-9]+' || echo "10") && \
     echo "Detected GCC version: $gcc_version" && \
-    if[ -f /usr/include/c++/$gcc_version/bits/stdc++.h ]; then \
-    g++ -std=c++17 -x c++-header /usr/include/c++/$gcc_version/bits/stdc++.h \
-        -o /usr/include/c++/$gcc_version/bits/stdc++.h.gch
+    if [ -f /usr/include/c++/$gcc_version/bits/stdc++.h ]; then \
+        echo "Precompiling stdc++.h..." && \
+        g++ -std=c++17 -x c++-header /usr/include/c++/$gcc_version/bits/stdc++.h \
+            -o /usr/include/c++/$gcc_version/bits/stdc++.h.gch; \
     else \
-       echo "bits/std++.h not found"; \    
+        echo "bits/stdc++.h not found, skipping precompilation."; \
     fi
+
 CMD ["tail", "-f", "/dev/null"]
